title: "That C# guy"
subtitle: Ingeniería de software + Ciencia de datos + MLOps
description: Un sitio en donde se habla a veces de programación, a veces de ciencia de datos y muchas veces de MLOps.
default-author: Antonio Feregrino
site-url: https://thatcsharpguy.com/
social:
  - name: GitHub
    link: https://github.com/lockdownblog/lockdown
post-routes:
    - /post/{}/index.html
    - /post/{}.html
tag-page-route: tag/{}/index.html
tag-index-route: tag/index.html
