name: Main pipeline

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout main repository  
        uses: actions/checkout@v2
        with:
            submodules: true

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # SDK Version to use; x will use the latest version of the 3.1 channel

      - name: Build website
        run: dotnet build --project ./lockdown/Lockdown/Lockdown.csproj -- run -p . -o _site

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs
          FOLDER: _site
          CLEAN: true
